@startuml
abstract "RandomGenerator" as C_0005626131955381280210
abstract C_0005626131955381280210 {
+~RandomGenerator() : void
..
{abstract} +generate() = 0 : double
{abstract} +generateUInt32() = 0 : unsigned int
{static} +getGeneratedNumberCount() : size_t
{abstract} +getName() const = 0 : std::string
{static} #incrGeneratedNumberCount() : void
{abstract} +isPseudoRandom() const = 0 : bool
{static} +resetGeneratedNumberCount() : void
{abstract} +setSeed(int seed) = 0 : void
__
}
class "RandomGeneratorFactory" as C_0006098685048331150840
class C_0006098685048331150840 {
+RandomGeneratorFactory(Type _type) : void
..
+generateRandomGenerator(int seed = 1) : RandomGenerator *
+getName() const : std::string
+isPseudoRandom() const : bool
+isThreadSafe() const : bool
__
}
class "Node" as C_0001746392397735786431
class C_0001746392397735786431 {
+Node(const std::string & label, const std::string & description, NodeIndex index) : void
+~Node() : void
..
+computeNodeState(NetworkState & network_state, NodeState & node_state) const : bool
+display(std::ostream & os) const : void
+generateLogicalExpression(LogicalExprGenContext & gen) const : void
+generateRawLogicalExpression() const : Expression *
+getAttributeExpression(const std::string & attr_name) const : const Expression *
+getAttributeExpressionMap() const : const std::map<std::string,const Expression *> &
+getAttributeString(const std::string & attr_name) const : std::string
+getAttributeStringMap() const : const std::map<std::string,std::string> &
+getDescription() const : const std::string &
+getIState(const Network * network, RandomGenerator * randgen) const : NodeState
+getIndex() const : NodeIndex
+getLabel() const : const std::string &
+getLogicalInputExpression() const : const Expression *
+getNodeBit() const : NetworkState_Impl
+getNodeState(const NetworkState & network_state) const : NodeState
+getRateDown(const NetworkState & network_state) const : double
+getRateDown(const NetworkState & network_state, const PopNetworkState & pop) const : double
+getRateDownExpression() const : const Expression *
+getRateUp(const NetworkState & network_state) const : double
+getRateUp(const NetworkState & network_state, const PopNetworkState & pop) const : double
+getRateUpExpression() const : const Expression *
+getReferenceState() const : NodeState
+getScheduledFlips() const : std::map<double,Expression *> *
+inGraph(bool _in_graph) : void
+inGraph() const : bool
{static} +isAugment() : bool
+isInputNode() const : bool
+isInternal(bool _is_internal) : void
+isInternal() const : bool
{static} +isOverride() : bool
+isReference() const : bool
+istateSetRandomly() const : bool
+makeMutable(Network * network) : void
+mutate(double value) : void
+reset() : void
+setAttributeExpression(const std::string & attr_name, const Expression * expr) : void
+setAttributeString(const std::string & attr_name, const std::string & str) : void
{static} +setAugment(bool _augment) : void
+setDescription(const std::string & _description) : void
+setIState(NodeState _istate) : void
+setIndex(NodeIndex new_index) : void
+setLogicalInputExpression(const Expression * logicalInputExpr) : void
+setNodeState(NetworkState & network_state, NodeState state) : void
{static} +setOverride(bool _override) : void
+setRateDownExpression(const Expression * expr) : void
+setRateUpExpression(const Expression * expr) : void
+setReference(bool _is_reference) : void
+setReferenceState(NodeState _referenceState) : void
+setScheduledFlips(std::map<double,Expression *> * _schedule) : void
+toString() const : std::string
__
}
class "Network" as C_0000440164721711273067
class C_0000440164721711273067 {
+Network() : void
+Network(const Network & network) : void
+~Network() : void
..
+operator=(const Network & network) : Network &
..
+cloneIStateGroup(std::vector<IStateGroup *> * _istate_group_list) : void
+compile(std::map<std::string,NodeIndex> * nodes_indexes = __null) : void
+defineNode(const std::string & label, const std::string & description = "") : Node *
+display(std::ostream & os) const : void
+displayHeader(std::ostream & os) const : void
+generateLogicalExpressions(std::ostream & os) const : void
+getIStateGroup() : std::vector<IStateGroup *> *
+getInputNodes() const : const std::vector<Node *> &
{static} +getMaxNodeSize() : size_t
+getNode(const std::string & label) : Node *
+getNode(NodeIndex node_idx) : Node *
+getNodeCount() const : size_t
+getNodes() const : const std::vector<Node *> &
+getNonInputNodes() const : const std::vector<Node *> &
+getOrMakeNode(const std::string & label) : Node *
+getSymbolTable() : SymbolTable *
+initStates(NetworkState & initial_state, RandomGenerator * randgen) : void
+isNodeDefined(const std::string & identifier) : bool
+isPopNetwork() : bool
+parse(const char * file = __null, std::map<std::string,NodeIndex> * nodes_indexes = __null, bool is_temp_file = false, bool useSBMLNames = false) : int
+parseExpression(const char * content = __null, std::map<std::string,NodeIndex> * nodes_indexes = __null) : int
+parseSingleExpression(const char * content, std::map<std::string,NodeIndex> * nodes_indexes = __null) : Expression *
+removeLastNode(const std::string & identifier) : void
+resetNodeDefinition() : void
+setNodeAsDefined(const std::string & identifier) : void
+toString() const : std::string
__
}
class "NetworkState" as C_0005946925854321740463
class C_0005946925854321740463 {
+NetworkState(const NetworkState_Impl & _state) : void
+NetworkState(const NetworkState & _state) : void
+NetworkState() : void
..
+operator=(const NetworkState & _state) : NetworkState &
..
+operator&(const NetworkState & mask) const : NetworkState
..
+applyMask(const NetworkState & mask, std::map<unsigned int,unsigned int> &) const : NetworkState
+computeNodeState(const Node * node, NodeState & node_state) : bool
+display(std::ostream & os, const Network * network) const : void
+displayJSON(std::ostream & os, const Network * network, const std::string & sep = " -- ") const : void
+displayOneLine(std::ostream & os, const Network * network, const std::string & sep = " -- ") const : void
+flipState(const Node * node) : void
+getName(const Network * network, const std::string & sep = " -- ") const : std::string
+getNetworkStates() const : std::set<NetworkState_Impl> *
+getNodeState(const Node * node) const : NodeState
+getState() const : NetworkState_Impl
{static} +getState(Node * node, const NetworkState_Impl & state) : NodeState
+hamming(Network * network, const NetworkState_Impl & state) const : unsigned int
+hamming(Network * network, const NetworkState & state) const : unsigned int
{static} +isPopState() : bool
{static} +nodeBit(NodeIndex node_index) : NetworkState_Impl
+reset() : void
+set() : void
+setNodeState(const Node * node, NodeState node_state) : void
__
}
class "RunConfig" as C_0005075511378526221526
class C_0005075511378526221526 {
+RunConfig() : void
+RunConfig(const RunConfig & other) : void
+~RunConfig() : void
..
+display(Network * network, time_t start_time, time_t end_time, std::ostream & os) const : void
+displayTrajectories() const : bool
+dump(Network * network, std::ostream & os, std::string version, bool header = true) const : void
+generateTemplate(Network * network, std::ostream & os, std::string version) const : void
+getCustomPopOutputExpression() const : const Expression *
+getDisplayTrajectories() const : bool
+getInitPop() const : unsigned int
+getMaxTime() const : double
+getPopBase() const : double
+getRandomGeneratorFactory() const : RandomGeneratorFactory *
+getSampleCount() const : unsigned int
+getSeedPseudoRandom() const : int
+getStatDistSimilarityCacheMaxSize() const : unsigned int
+getStatDistTrajCount() const : unsigned int
+getStatdistClusterThreshold() const : double
+getThreadCount() const : unsigned int
+getTimeTick() const : double
{static} +getVerbose() : unsigned int
+hasCustomPopOutput() const : bool
+isDiscreteTime() const : bool
+parse(Network * network, const char * file = __null) : int
+parseExpression(Network * network, const char * expr) : int
+setCustomPopOutputExpression(Expression * expr) : void
+setParameter(const std::string & param, double value) : void
+setSeedPseudoRandom(int seed) : void
{static} +setVerbose(unsigned int level) : void
+useGlibcRandGen() const : bool
+useMTRandGen() const : bool
+usePhysRandGen() const : bool
__
}
class "MetaEngine" as C_0007414202677506663061
class C_0007414202677506663061 {
+MetaEngine(Network * network, RunConfig * runconfig) : void
+~MetaEngine() : void
..
+computeTH(Network * _network, const std::vector<double> & nodeTransitionRates, double total_rate) const : double
+getElapsedCoreRunTime() const : long long
+getElapsedEpilogueRunTime() const : long long
+getElapsedStatDistRunTime() const : long long
+getTargetNode(Network * _network, RandomGenerator * random_generator, const std::vector<double> & nodeTransitionRates, double total_rate) const : NodeIndex
+getUserCoreRunTime() const : long long
+getUserEpilogueRunTime() const : long long
+getUserStatDistRunTime() const : long long
{static} +init() : void
{static} +loadUserFuncs(const char * module) : void
__
#discrete_time : bool
#elapsed_core_runtime : long long
#elapsed_epilogue_runtime : long long
#elapsed_statdist_runtime : long long
#max_time : double
#network : Network *
#reference_state : NetworkState
#refnode_count : unsigned int
#refnode_mask : NetworkState
#runconfig : RunConfig *
#sample_count : unsigned int
#statdist_trajcount : unsigned int
#thread_count : unsigned int
#thread_elapsed_runtimes : std::vector<long long>
#time_tick : double
#user_core_runtime : long long
#user_epilogue_runtime : long long
#user_statdist_runtime : long long
}
abstract "FinalStateDisplayer" as C_0005888550321102446117
abstract C_0005888550321102446117 {
+~FinalStateDisplayer() : void
..
{abstract} +begin() = 0 : void
{abstract} +displayFinalState(const NetworkState_Impl & state, double value) = 0 : void
{abstract} +end() = 0 : void
__
}
class "FinalStateSimulationEngine" as C_0005542738902560728554
class C_0005542738902560728554 {
+FinalStateSimulationEngine(Network * network, RunConfig * runconfig) : void
+~FinalStateSimulationEngine() : void
..
+displayFinal(FinalStateDisplayer * displayer) const : void
+displayRunStats(std::ostream & os, time_t start_time, time_t end_time) const : void
+getFinalNodes() const : const std::unordered_map<Node *,double>
+getFinalTime() const : double
+run(std::ostream * output_traj) : void
__
{static} +VERSION : const std::string
}
class "FinalStateArgWrapper" as C_0018345836352791587643
class C_0018345836352791587643 {
+FinalStateArgWrapper(FinalStateSimulationEngine * mabest, unsigned int start_count_thread, unsigned int sample_count_thread, RandomGeneratorFactory * randgen_factory, int seed, FixedPoints * final_state_map, std::ostream * output_traj) : void
__
+final_state_map : FixedPoints *
+mabest : FinalStateSimulationEngine *
+output_traj : std::ostream *
+randgen_factory : RandomGeneratorFactory *
+sample_count_thread : unsigned int
+seed : int
+start_count_thread : unsigned int
}
C_0006098685048331150840 ..> C_0005626131955381280210
C_0001746392397735786431 ..> C_0000440164721711273067
C_0001746392397735786431 ..> C_0005626131955381280210
C_0001746392397735786431 ..> C_0005946925854321740463
C_0000440164721711273067 ..> C_0005946925854321740463
C_0000440164721711273067 ..> C_0005626131955381280210
C_0000440164721711273067 --> C_0001746392397735786431 : -node_map
C_0000440164721711273067 --> C_0001746392397735786431 : -input_nodes
C_0000440164721711273067 --> C_0001746392397735786431 : -non_input_nodes
C_0000440164721711273067 --> C_0001746392397735786431 : -nodes
C_0005946925854321740463 ..> C_0001746392397735786431
C_0005946925854321740463 ..> C_0000440164721711273067
C_0005075511378526221526 ..> C_0000440164721711273067
C_0005075511378526221526 --> C_0006098685048331150840 : -randgen_factory
C_0007414202677506663061 ..> C_0005626131955381280210
C_0007414202677506663061 --> C_0000440164721711273067 : #network
C_0007414202677506663061 --> C_0005075511378526221526 : #runconfig
C_0007414202677506663061 o-- C_0005946925854321740463 : #reference_state
C_0007414202677506663061 o-- C_0005946925854321740463 : #refnode_mask
C_0005542738902560728554 ..> C_0005626131955381280210
C_0005542738902560728554 ..> C_0006098685048331150840
C_0005542738902560728554 ..> C_0000440164721711273067
C_0005542738902560728554 ..> C_0005075511378526221526
C_0005542738902560728554 ..> C_0001746392397735786431
C_0005542738902560728554 ..> C_0005888550321102446117
C_0005542738902560728554 o-- C_0005946925854321740463 : -internal_state
C_0005542738902560728554 --> C_0018345836352791587643 : -arg_wrapper_v
C_0007414202677506663061 <|-- C_0005542738902560728554
C_0018345836352791587643 --> C_0005542738902560728554 : +mabest
C_0018345836352791587643 --> C_0006098685048331150840 : +randgen_factory

'Generated with clang-uml, version 0.6.2-27-g4e76f03
'LLVM version Ubuntu clang version 18.1.3 (1ubuntu1)
@enduml
